# no keys without a value or cherrypy will fail to start
# ${ENV_VAR} to get from env var

metrics_poller:
  redis_host: localhost
  redis_port: 6379
  redis_queue_db: 0
  get_definitions_interval_sec: 600
  bucketDuration_sec: 300
  collect_metrics:
    gauge:
      - cpu/request
      - cpu/usage_rate
      - memory/request
      - memory/usage
      - filesystem/usage
      - network/rx_rate
      - network/tx_rate

hawkular_metrics_client:
  scheme: https
  host: metrics-openshift-infra.192.168.100.5.xip.io
  port: 443
  path: hawkular/metrics
  token: ${BEARER_TOKEN}

database:
  cp_pool_size: 20
  driver: mysql+pymysql
  host: localhost
  db: hawkular_billing
  user: root
  password: asdf
