# no keys without a value or cherrypy will fail to start

metrics_poller:
  redis_host: localhost
  redis_port: 6379
  redis_queue_db: 0
  redis_lock_db: 1
  get_namespaces_interval: 10

hawkular_metrics_client:
  scheme: https
  host: metrics-openshift-infra.192.168.100.5.xip.io
  port: 443
  path: hawkular/metrics
  token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaGF3a3VsYXItYmlsbGluZy1yZWFkZXItdG9rZW4tN3JmYnciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiaGF3a3VsYXItYmlsbGluZy1yZWFkZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5MzVmYjk5OC01NjAwLTExZTctYWY1Mi01NDA0YTYxMDFhYzkiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bXlwcm9qZWN0Omhhd2t1bGFyLWJpbGxpbmctcmVhZGVyIn0.igJ7fNM83hAZ0NvvCRrckFs5HgphbqdioY7RZcQfRJfZ4I3qey4WeerCKrfw5zplq2oedVeUEgF3QNJ-qGbIDoDYuOrjY4sdSap_PV3_98XygFRKZ0PLeT3VXQHLBf-WSxtTes-qQYcPq9tXnQaGBk3oDgoXuWBOmMHtmHWmpfRCJMMDhWkRkuCnVF_IR5E5dPV3-MkrTBrYLf2hrSZDdGWkfBITPPc5QOr4vLG1r2gkd4-ug5Pb8dItBEnAhReiRoy3vlGsVf2e2mxvYBeSoTsQpxbt0uhUHDxrJk0tWqHZzH2OBQmFkUu4LJOueTky0mWMZHY6GXyGKIfcA15Q2g

database:
  driver: mysql+pymysql
  host: localhost
  db: hawkular_billing
  user: root
  password: asdf
