# no keys without a value or cherrypy will fail to start

metrics_poller:
  redis_host: localhost
  redis_port: 6379
  redis_queue_db: 0
  redis_lock_db: 1
  get_definitions_interval: 30
  get_metric_data_interval: 60

hawkular_metrics_client:
  scheme: https
  host: metrics-openshift-infra.192.168.100.5.xip.io
  port: 443
  path: hawkular/metrics
  token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaGF3a3VsYXItYmlsbGluZy1yZWFkZXItdG9rZW4tNGhjMGMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiaGF3a3VsYXItYmlsbGluZy1yZWFkZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJlYWRlY2RhNC01NmFkLTExZTctYTU1ZC01NDA0YTYxMDFhYzkiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bXlwcm9qZWN0Omhhd2t1bGFyLWJpbGxpbmctcmVhZGVyIn0.rK5je2yrLCZuUJaDHinq2csc5JMQdAd-QNdnIWVT884kXCn2RzioqI68mOYFu9lPFpP84ahMKrmSMSjh3ieONBAekUDOQ9IIij91loJbXHaw-I6OHm8_f4tyYWgN8EA-PV_c1Hi-UImfEOKtLl46R3Qs-rn9cDRUrfRv5Nxf8ruqLMt3rUULCe1HkbdcjqH9fIsqxoGugzcsrfEhB_MKAzdcvq9wAuo1o4oxSfzGgQAg29O2CEZgkRFp3Z1OKa7vTkawp19FN-qouO6acZcHCex9eP2nPVxjOKiDGWFrvBiBhxleQh2H8k6bB9bTeM8BChstSLpl0rgBT6mV2JL5AQ

database:
  pool_size: 100
  driver: mysql+pymysql
  host: localhost
  db: hawkular_billing
  user: root
  password: asdf
