apiVersion: v1
kind: Template
metadata:
  name: hawkular-billing-template
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
      name: hawkular-billing-reader
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: hawkular-billing-cluster-reader
  roleRef:
    name: cluster-reader
  subjects:
  - kind: ServiceAccount
    name: hawkular-billing-reader
    namespace: myproject
